Add SVGMetadata API
eclipse-glsp/glsp-client pull request #239
Opened 2023-04-02 17:29 UTC by haydar-metin

https://github.com/eclipse-glsp/glsp-playwright/pull/1

2023-04-05 08:15 UTC, martin-fleck-at commented
@haydar-metin I'll try to have a look a bit later that week. Could you please resolve the merge conflicts? Thank you!

2023-04-10 20:14 UTC, martin-fleck-at requested changes
Hi @haydar-metin, the change looks good to me technically. I'd even suggest to put the module in the general default modules as it just adds some metadata. However, I think we need to adapt the copyright header - at least the year - and maybe the copyright owner as well.

2023-04-10 20:14 UTC, martin-fleck-at commented on examples/workflow-glsp/src/di.config.ts
> +    container.load(svgMetadataModule);
I think this module is generic and useful enough to be added to the DEFAULT_MODULES.

2023-04-10 20:14 UTC, martin-fleck-at commented on packages/client/src/features/svg-metadata/metadata-placer.ts
> + * Copyright (c) 2020-2022 EclipseSource and others.
See other copyright header comment.

2023-04-16 12:17 UTC, haydar-metin commented on packages/client/src/features/svg-metadata/di.config.ts
> + * Copyright (c) 2020-2022 EclipseSource and others.
Not really, however, in my proposal it says that the whole thesis will be contributed to EclipseSource, therefore I do not think that any problems will arise.

2023-04-17 08:23 UTC, martin-fleck-at requested changes
Thank you for the update! I noticed to more things now that I had another look. And just to confirm: Having the copyright contribution as 'EclipseSource and others' is fine?

2023-04-17 08:23 UTC, martin-fleck-at commented on packages/client/src/features/svg-metadata/di.config.ts
> +import '../../../css/decoration.css';
```suggestion
```

2023-04-17 08:23 UTC, martin-fleck-at commented on packages/client/src/features/svg-metadata/di.config.ts
> +const svgMetadataModule = new ContainerModule((bind, _unbind, isBound) => {
```suggestion
const svgMetadataModule = new ContainerModule(bind => {
```

2023-04-20 15:31 UTC, martin-fleck-at commented
@haydar-metin If you confirm the copyright, I think we can merge this change.

2023-04-27 07:16 UTC, martin-fleck-at approved these changes
Thank you for the update! LGTM!

2023-04-27 07:17 UTC, merged