Add keyboard support for moving and zooming elements and viewport
eclipse-glsp/glsp-client pull request #241
Opened 2023-04-19 17:58 UTC by aylin-sarioglu

This PR is part of my master thesis and introduces the **move** and **zoom** functionality.

## Examples 

### Move elements
1. Select one or multiple elements
2. Use the arrow keys to move the element(s) accordingly

### Move viewport
1. Focus is on viewport , no elements are selected
2. Use the arrow keys to move the viewport accordingly
 
### Zoom  elements
1. Select one or multiple elements
2. Use `+` or `-` to zoom in/out  into the direction of the element or elements
3. Use `CTRL + 0` to reset to default zoom level

### Zoom  viewport
1. Focus is on viewport , no elements are selected
2. Use `+` or `-` to zoom in/out in viewport
3. Use `CTRL + 0` to reset to default zoom level

@martin-fleck-at, @ndoschek

2023-05-05 08:22 UTC, ndoschek commented
Hi @aylin-sarioglu, thank you very much for your contribution. I'll look at it at the beginning of next week.
Could you please rebase to latest master in the meantime to resolve the conflicts? Thank you :)

2023-05-10 10:56 UTC, ndoschek commented on packages/client/src/features/tools/viewport/movement-key-tool.ts
> +    protected grid = { x: 20, y: 20 };
I'm not a big fan of magic numbers in general. But in this case it is used if there is no available `GridSnapper`, right? Could you please add some documentation here and for example extract the default values into static members, something like:

```suggestion
    static readonly defaultMoveX = 20;
    static readonly defaultMoveY = 20;

    protected grid = { x: MoveKeyListener.defaultMoveX, y: MoveKeyListener.defaultMoveY };
```

2023-05-10 10:57 UTC, ndoschek commented on packages/client/src/features/tools/viewport/movement-key-tool.ts
> +            this.grid = this.tool.snapper?.grid;
```suggestion
            this.grid = this.tool.snapper.grid;
```

2023-05-14 18:35 UTC, aylin-sarioglu commented on packages/client/src/features/tools/viewport/zoom-key-tool.ts
> +    }
The reason for using event.key for '+' is that the `matchesKeystroke` from sprotty has no 'Add' or something similiar declared for '+'. The keycode for '+'is 187, which is falsly declared as `addKeyCode('Equal', 187);` in [`keyboard.ts.`](https://github.com/eclipse-sprotty/sprotty/blob/master/packages/sprotty/src/utils/keyboard.ts)

2023-06-02 13:30 UTC, ndoschek requested changes
Hi @aylin-sarioglu, thanks for the great improvements :sparkles:!

Overall it looks good to me, I added a few minor comments inline.
Once they are resolved, I guess we are close to merging this pr :+1: 

And one thing, as I am looking again at the code, perhaps it would be a good idea to nest the `move-zoom` and `view-key-tools` features inside the new `accessibility` folder now as well-
This would group all the features in the accessibility context in one directory, which would be useful for later maintenance after all.

I'd suggest to go with this structure:
![image](https://github.com/eclipse-glsp/glsp-client/assets/47414588/26bd667a-973f-47f3-98f6-3bfd70a5e3c8)

2023-06-02 13:30 UTC, ndoschek commented on packages/client/src/index.ts
> +    glspMoveZoomModule
Please also export the `glspAccessibilityModule` here.

2023-06-02 13:30 UTC, ndoschek commented on packages/client/src/features/move-zoom/zoom-handler.ts
> +    protected readonly throttledHandleViewportZoom = throttle((action: ZoomViewportAction) => this.handleZoomViewport(action), 500);
Thanks for this fix!
It feels better now, but could we use a lower timeout here?
I tested with 150, this also feel less laggy. wdyt?

2023-06-02 13:30 UTC, ndoschek commented on packages/client/src/features/move-zoom/move-handler.ts
> +    handle(action: Action): void | Action | ICommand {
Please also use the throttling of actions for the handlers in this file as well.

2023-06-02 13:30 UTC, ndoschek commented on packages/client/src/features/move-zoom/move-handler.ts
Please add short descriptions to the actions and handlers in this file.

2023-06-02 13:30 UTC, ndoschek commented on packages/client/src/features/move-zoom/zoom-handler.ts
Please add short descriptions to the actions and handlers in this file.

2023-06-02 13:34 UTC, ndoschek commented on packages/client/src/features/tools/viewport/zoom-key-tool.ts
> +    }
Thanks for clearing that up, then that's fine! Perhaps you could add a short comment there, that this information isn't lost?

2023-06-05 06:56 UTC, ndoschek reviewed
Thank you @aylin-sarioglu for the quick updates!
Looks good to me, I just have one minor comment left.
If that's fixed, we are good to go from my POV :)

2023-06-05 06:56 UTC, ndoschek commented on packages/client/src/features/tools/di.config.ts
> +
Please omit this change as there are no other changes on this file, thanks!

2023-06-05 07:07 UTC, ndoschek commented on packages/client/src/features/accessibility/move-zoom/move-handler.ts
> +    protected readonly throttledHandleElementMove = throttle((action: MoveElementAction) => this.handleMoveElement(action), 500);
The timeouts in `move-handler.ts` and `zoom-handler.ts` differ in the different handlers. Could you please align them, thanks!

2023-06-06 09:19 UTC, ndoschek approved these changes
Thank you @aylin-sarioglu for the quick updates and the reporting of the bug! :+1:

2023-06-06 09:20 UTC, merged