Introduce list of keyboard shortcuts
eclipse-glsp/glsp-client pull request #260
Opened 2023-07-07 18:01 UTC by aylin-sarioglu

This PR is part of my diploma research conducted at the [Model Engineering lab](https://me.big.tuwien.ac.at/) of TU Wien in the [Business Informatics Group](https://www.big.tuwien.ac.at/). It introduces a list of existing keyboard shortcuts.

## Example

### Search
1. Focus is on viewport.
2. Use the shortcut  `ALT+H` to display the list of keyboard shortcuts.

Part of https://github.com/eclipse-glsp/glsp/issues/1029

2023-07-12 12:15 UTC, ndoschek requested changes
Hi @aylin-sarioglu! Thanks for this contribution, this is a good next step towards making GLSP more accessible to many users! :tada: 
Overall the code looks good to me, I added some comments inline.

Other than that, I'd like to add some suggestions, but they are not really blocking IMO:
- The styling of the help overview could be improved from my POV. As mentioned inline, it could help to use a tabular structure instead to get a more homogeneous styling. Also, I would try to reduce the large margins in between headings and sections. This way we could perhaps achieve that the user does not have to scroll to gather all information (although scrolling works via the keyboard as well).
  - The actual CSS styling could be aligned a bit more to the tool-palette, e.g. style headers in the same way as the tool palette does for example. This way we would get a more integrated UX feel, but this is a personal preference. Let me know what you think.
- I would find it beneficial if `Alt+H` would toggle the help, i.e. if opened, `Alt+H` would close the help, not only the Escape key (or the X button).

Thanks again!

2023-07-12 12:15 UTC, ndoschek commented on packages/client/src/features/accessibility/key-shortcut/key-shortcut.ts
I'm a little unsure about the namings of the interface, action, provider and the class here. I would prefer some pre- or suffix to indicate those shortcuts are linked to the accessibility feature. I'm afraid someone could confuse this with the default key tools.

2023-07-12 12:15 UTC, ndoschek commented on packages/client/src/features/accessibility/key-shortcut/key-shortcut.ts
> +export class KeyShortcut extends AbstractUIExtension implements IActionHandler {
The class should name indicate that it provides the helper UI of the shortcuts.

2023-07-12 12:15 UTC, ndoschek commented on packages/client/src/features/accessibility/view-key-tools/movement-key-tool.ts
> +                    { shortcuts: ['⬅ ⬆ ➡ ⬇'], description: 'Move element or viewport', group: 'Move', position: 0 }
I'd suggest to add spaces in between the arrows
```suggestion
                    { shortcuts: ['⬅  ⬆  ➡  ⬇'], description: 'Move element or viewport', group: 'Move', position: 0 }
```

2023-07-20 14:08 UTC, ndoschek commented
Hi @aylin-sarioglu!
Could you please rebase your branch, as there have been some changes in the framework with cause some conflicts, but they were mostly renames, so it should hopefully not cause too much trouble on your end.
Can you roughly predict when you will be able to address the comments? TIA, Nina

2023-07-20 19:20 UTC, aylin-sarioglu commented
> Hi @aylin-sarioglu! Could you please rebase your branch, as there have been some changes in the framework with cause some conflicts, but they were mostly renames, so it should hopefully not cause too much trouble on your end. Can you roughly predict when you will be able to address the comments? TIA, Nina

Hi @ndoschek, Yes, I'll do it and  I will fix the comments this weekend.

2023-07-24 11:04 UTC, tortmayr reviewed
I was curious and also had a look at the new accesibility feature.
Very nice work!

If have a few minor comments regarding code style etc.  but nothing that would block merging.
@ndoschek It's up to you whether you want to merge as is or fix the mentioned issues before.

2023-07-25 15:18 UTC, ndoschek commented
Thank you for the update @aylin-sarioglu!
Would be great if you could address Tobias' comments as well if you find time.
(Thanks for the review @tortmayr!)

2023-07-26 10:57 UTC, aylin-sarioglu commented
> Thank you for the update @aylin-sarioglu! Would be great if you could address Tobias' comments as well if you find time. (Thanks for the review @tortmayr!)

Hi @ndoschek , the remaining comments are also fixed now.

2023-07-26 12:48 UTC, ndoschek approved these changes
Thank you @aylin-sarioglu, looks good to me now! :+1:

2023-07-26 12:48 UTC, merged