Add real progress reporting in favor of timeout
eclipse-glsp/glsp-client pull request #265
Opened 2023-07-12 15:12 UTC by planger

* Remove `ServerMessageAction.timeout`
* Add actions for reporting progress

https://github.com/eclipse-glsp/glsp/issues/1019

2023-07-12 22:05 UTC, tortmayr requested changes
Change looks mostly good to me. I have a few minor nitpicks.
Will we are at it could please either open an issue to update the protocol on the 2.0 branch of the [website-source repo](https://github.com/eclipse-glsp/glsp-website-source/tree/2.0) or provide a PR directly?

2023-07-12 22:05 UTC, tortmayr commented on packages/protocol/src/action-protocol/client-notification.ts
> +    export function create(
I don't know if we have other occurrences of this pattern but if the create function has one required and one optional parameter wrapping the optional parameter in an options object seems a bit overkill to me.

2023-07-13 12:16 UTC, planger commented
@tortmayr Thanks for the feedback, I've addressed your comments and updated the other changes accordingly.
Also I've extended the description of https://github.com/eclipse-glsp/glsp/issues/1019 to list all required changes, including the one for the website.

2023-07-13 12:16 UTC, tortmayr approved these changes
LGTM! 👍🏼

2023-07-13 13:09 UTC, merged