Support rendering of ghost element when creating elements
eclipse-glsp/glsp-client pull request #301
Opened 2023-11-12 22:10 UTC by martin-fleck-at

- Introduce new element template module -- Adding new elements to the diagram based on templates -- Removing templates again

- Support local bounds calculation for client-only added elements -- Must trigger RequestBounds for hidden view calculation -- Must not modify main view until ComputedBounds response is handled -- Mark ResizeHandles as not to be considered for bounds calculation -- Fix positioning of decorations for hidden view calculation

- Add ghost element extension to tool palette -- Optional ghost element field in the trigger node creation action -- Ghost element is added as feedback to the mouse cursor -- If ghost element is dynamic, templates (palette items) are reloaded

- Bonus: Re-calculate local bounds for resize behavior

Fixes https://github.com/eclipse-glsp/glsp/issues/1159

---

https://github.com/eclipse-glsp/glsp-client can

2023-11-13 10:00 UTC, tortmayr requested changes
In general the change works really well!
I have a couple of inline comments and suggestions but other than that everything looks good to me.

Could you please make sure that all of you newly introduced functions,classes etc. are added to the main index and that add (high level) jsdoc to them?

While marking the local-only `RequestBounds/ComputedBounds` as server actions works it is not really intuitive and rather confusing. I'm wondering whether we should add the a more generic approach here to explicitly restrict a specific action that is normally handle on both client and server to one target.

2023-11-13 11:39 UTC, martin-fleck-at commented on packages/client/src/features/bounds/glsp-hidden-bounds-updater.ts
> +                if (child.getAttribute(ATTR_BBOX_ELEMENT) !== null) {
No longer relevant after some refactoring.

2023-11-13 11:39 UTC, martin-fleck-at commented on packages/client/src/base/args-feature.ts
> +    if (element === undefined || !isArgsAware(element)) {
Good idea!

2023-11-13 11:39 UTC, martin-fleck-at commented on packages/client/css/ghost-element.css
> +    /* we are a true ghost so we do not want to be used as a target for any mouse event */
Good idea!

2023-11-13 11:39 UTC, martin-fleck-at commented on packages/client/src/features/bounds/glsp-hidden-bounds-updater.ts
> +        if (isSVGGraphicsElement(elm) && elm.getAttribute(ATTR_HIDDEN_BBOX_ELEMENT) !== null) {
No longer relevant after some refactoring.

2023-11-13 11:40 UTC, martin-fleck-at commented on packages/client/src/features/bounds/set-bounds-feedback-command.ts
> +export interface SetBoundsFeedbackAction extends Omit<SetBoundsAction, 'kind'> {
Done.

2023-11-13 11:42 UTC, martin-fleck-at commented on packages/client/src/features/decoration/decoration-placer.ts
> +                x: -GlspDecorationPlacer.DECORATION_OFFSET.x,
During the main view rendering, the element bounds are all `-1` so the result was always to position the decoration in the top left corner. However, for the local bounds computation the bounds were already correctly calculated, e.g., 200x100, so the decoration was placed way to the bottom right. I'm not sure why we multiply it with width/height anyway but if there is a particular reason you are aware of, please let me know.

2023-11-13 11:46 UTC, martin-fleck-at commented on packages/client/src/features/element-template/add-template-element.ts
> +export function applyCssClasses(source?: string[], toAdd?: string[], toRemove?: string[]): string[] {
Absolutely correct. I kept the function local and added all the other exports to the index, thank you catching this!

2023-11-13 11:49 UTC, martin-fleck-at commented on packages/client/src/features/tool-palette/tool-palette.ts
> +        } else {
I went for the type check, thanks!

2023-11-13 11:52 UTC, martin-fleck-at commented on packages/client/src/features/tool-palette/tool-palette.ts
> -    protected handleSetContextActions(action: SetContextActions): void {
Good idea, I added it!

2023-11-13 11:52 UTC, martin-fleck-at commented on packages/client/src/features/tool-palette/tool-palette.ts
> +        this.dynamic = !!this.paletteItems.find(item => this.hasDynamicAction(item));
Done.

2023-11-13 11:53 UTC, martin-fleck-at commented on packages/client/src/features/tool-palette/tool-palette.ts
> +        return !!item.children?.find(child => this.hasDynamicAction(child));
Done.

2023-11-13 11:53 UTC, martin-fleck-at commented on packages/client/src/features/tools/node-creation/node-creation-tool.ts
> +            trackingListener = new MouseTrackingElementPositionListener(getTemplateElementId(ghostElement.template), this, 'middle');
Done!

2023-11-13 11:59 UTC, martin-fleck-at commented on packages/client/src/utils/layout-utils.ts
> +export function minWidth(element: GModelElement): number {
I think I needed it for the ghost element at some point but I no longer do. So I reverted those changes.

2023-11-14 07:54 UTC, martin-fleck-at commented
@tortmayr I agree that this would be a nice feature to have. However, currently there is no way to simply reload trigger actions and then to uniquely identify them so we can easily replace the action and template that we are currently using. So I pulled this out into an enhancement issue (https://github.com/eclipse-glsp/glsp/issues/1161) as it would require more work that I want to consider out of scope for this ticket. What do you think?

2023-11-20 23:23 UTC, tortmayr approved these changes
LGTM! Thanks!

2023-11-20 23:23 UTC, merged