GLSP-1393 Align Interface usage across *Manager classes
eclipse-glsp/glsp-client pull request #388
Opened 2024-08-23 12:33 UTC by ndoschek

#### What it does

- Align interface + symbol usage for *Manager classes
  - `ChangeBoundsManager`, `GridManager`, `DebugManager`
- Use bindAsService to ensure backward compatibility
- Update injects to use the symbol instead of the actual manager class

Resolves https://github.com/eclipse-glsp/glsp/issues/1393

#### How to test

Changing bounds, grid toggling and debug mode toggling should work as before, this should not impact the functionality at all.

#### Follow-ups

--

#### Changelog

-   [x] This PR should be mentioned in the changelog
-   [ ] This PR introduces a breaking change (if yes, provide more details below for the changelog and the migration guide)

2024-08-29 11:43 UTC, martin-fleck-at requested changes
Thank you very much Nina! The code looks good to me in general, I just have some worries regarding the injection - which in my opinion should use the interfaces.

@tortmayr Are you happy with the general split between type/interface/class?

2024-08-29 11:43 UTC, martin-fleck-at commented on examples/workflow-glsp/src/workflow-startup.ts
> +    @inject(TYPES.IGridManager) @optional() protected gridManager?: GridManager;
```suggestion
    @inject(TYPES.IGridManager) @optional() protected gridManager?: IGridManager;
```

If we are already introducing interfaces for the manager classes, we should only rely on those interfaces when injecting that class. This is true for all injection points for all manager classes.

2024-08-29 14:29 UTC, tortmayr commented
>@tortmayr Are you happy with the general split between type/interface/class?

In general yes. I think this is the best solution to give adopters full flexibility for customizations. We just have to make sure that we keep interface and default implementation in sync if we make future changes. i.e. every public method/field of the default implementation needs to already be added to the interface.

I think this is a pattern that we could extend to our other services as well. (e.g. the selection service).

2024-09-02 12:20 UTC, ndoschek commented
Thanks for the feedback! I'll address it in the course of the upcoming week!

2024-09-04 12:49 UTC, ndoschek commented
Thank you both for your comments. I’ve updated my commit and created a follow-up issue (GH-1400) to apply the same pattern to other services, as Tobias suggested.

2024-09-09 11:50 UTC, martin-fleck-at approved these changes
Thank you, Nina! Everything still looks good to me!

2024-09-09 11:50 UTC, merged