GH-1377: Extract move and zoom features from accessibility to own module
eclipse-glsp/glsp-client pull request #396
Opened 2024-11-19 13:53 UTC by haydar-metin

#### What it does

Works on https://github.com/eclipse-glsp/glsp/issues/1377

#### How to test

Use the arrow keys to move the viewport / elements.
Use +/- to zoom in and out.

#### Follow-ups

#### Changelog

-   [x] This PR should be mentioned in the changelog
-   [x] This PR introduces a breaking change (if yes, provide more details below for the changelog and the migration guide)

The move and zoom features have been moved to their own modules. They are now enabled by default.

2024-11-19 14:17 UTC, haydar-metin commented
@tortmayr after some thought, do we even require tools for moving/zooming? Maybe `moveElement` would require it, but moving the viewport and zooming shouldn't need a tool or?

2024-11-19 15:19 UTC, tortmayr commented
@Haydar I agree. Currently zooming/scrolling via mouse is provided by the `viewportModule`. This module bind the mouse listeners directly instead of using tools. This means that those listeners are always on (independent of the activation state of the tool manager). Listeners that provide the same functionality via keyboard should probably als be bound directly. 
Otherwise we end up in an inconsistent state. (e.g. during edge creation zooming via mouse would be possible, but zooming via keyboard not (because default tools are disabled at that point).

So we should not use tools for zooming/moving.
For the move-tool its a different story, here a tool definitely make sense but maybe we should integrate this into the change bounds tool instead of having a separate tool just for keyboard movement

Thinking about it maybe it even makes sense to integrate the keyboard functionality for zooming/moving/scrolling directly into the corresponding default module (viewportModule, changeBoundsToolModule) instead of having extra a11y modules for them.
WDYT?

2024-11-20 14:57 UTC, haydar-metin commented
@tortmayr sounds good to me! I did the following:

- `MoveElementHandler` (ActionHandler) moved to `bounds`, as we don't have a `changeBounds` container module.
- `MoveElementKeyListener` moved to `change-bounds-tool`
- `MoveViewport*`, `Zoom**` moved to `viewport`

2024-12-06 05:30 UTC, tortmayr commented
@haydar-metin  Thanks for providing this change.
If its ok for you I will take a look at this PR after the 2.3 release is completed (planned until the end of next week).
Since this PR only partially addresses  https://github.com/eclipse-glsp/glsp/issues/1377  and also introduces some changes to the protocol API we should probably not include it in the current release.
We can then use the next release cycle to further work on https://github.com/eclipse-glsp/glsp/issues/1377 .

2025-02-21 08:01 UTC, tortmayr commented on packages/client/src/features/accessibility/view-key-tools/grid-zoom-key-tool.ts
> +export class GridZoomTool implements Tool {
Maybe we rename this use `GridCellZoomTool` to avoid potential confusion with the `Grid` API used for snapping?

2025-02-21 08:04 UTC, tortmayr commented on packages/protocol/src/action-protocol/element-move.ts
> +export interface MoveElementRelativeAction extends Action {
This action should not be part of the client-server protocol. Only a limited subset of client-side only actions are part of the protocol. The `MoveElementRealtiveAction` is defacto a feedback action. Dispatching this from the server-side does not make sense. (Movement changes on the server side should typically be operations)

2025-02-21 08:30 UTC, tortmayr commented on packages/client/src/features/change-bounds/move-element-key-listener.ts
> +        const selectedElementIds = this.selectionService.getSelectedElementIDs();
Need to be filtered so that only elements that have are actually moveable (`isMoveable` utility function) are moved.

2025-02-21 08:51 UTC, tortmayr commented
I also noticed a minor issue with the `MoveElementsHandler`: When moving to the borders of the diagram the handler adjusts the viewport accordingly. Currently this only works as expected when moving to the left or to the top.
In the other directions the canvas only starts moving once the (0.0) point of the element reaches the canvas limit.
Could you maybe fix this as part of this PR. Should only be a minor change where we also have to consider the elements width/height when moving in positive x/y directions:


https://github.com/user-attachments/assets/39619f0d-c004-4b02-83b2-98b51b261526

2025-02-21 08:53 UTC, tortmayr commented
Since we have protocol changes here and potentially more are to come please create a follow-up ticket that we have to update the[ protocol doc on the website](https://eclipse.dev/glsp/documentation/protocol/) once the a18y epic is completed.

I like the viewport adjustsments if we reach the canvas bounds on move. Maybe we should add the same functiallity to the change bounds mouse move tool (follow-up).

2025-02-21 08:55 UTC, tortmayr commented on packages/client/src/features/accessibility/view-key-tools/grid-zoom-key-tool.ts
> +                    viewportAction = this.zoomKeyListener.setNewZoomFactor(this.editorContextService.modelRoot, ZoomFactor.Default.OUT);
Maybe we should provide the ZoomFactor. in/out properties via a injectable options?
This would make it easier for adopters to customize

2025-02-21 09:15 UTC, haydar-metin commented on packages/client/src/features/viewport/viewport-modules.ts
> +        configureActionHandler(context, ZoomElementAction.KIND, ZoomElementHandler);
Use tools

2025-03-12 11:05 UTC, tortmayr commented on packages/client/src/base/ui-extension/ui-extension.ts
> +    protected toDisposeOnHide = new DisposableCollection();
Nice addition! 👍🏼

2025-03-12 11:26 UTC, tortmayr requested changes

2025-03-12 11:26 UTC, tortmayr commented on packages/client/src/features/change-bounds/resize/resize-tool.ts
> +        const selectedElementsIds = this.selectionService.getSelectedElementIDs();
Filter down to resizeable elements

2025-03-12 11:26 UTC, tortmayr commented on packages/client/src/features/shortcuts/shortcuts-manager.ts
> +import type { ShortcutRegistration } from './shortcuts-model';
No need to have a separate file just for one interface.
Can be moved in here

2025-03-12 11:26 UTC, tortmayr commented on packages/client/src/features/shortcuts/shortcuts-manager.ts
> +/********************************************************************************
I think we should move this functionality into the default module (i.e. the base package).
Having it as a dedicated feature module means that adopters could choose to remove/not load this module.
This would break all services that inject the shortcut manager

2025-03-12 11:26 UTC, tortmayr commented on packages/client/src/features/viewport/viewport-handler.ts
> +        if (ZoomAction.is(action)) {
Nit: Unncessary typecheck. If we have only one action that is handled you can define the correct type in the method signature directly

```ts
handle(action: ZoomViewportAction)
````

2025-03-12 11:26 UTC, tortmayr commented on packages/client/src/features/viewport/viewport-tool.ts
> +export class ViewportTool extends BaseTool {
Maybe rename it to `ViewportKeyTool` and add  short doc comment to mention that this tool only handles keyboard related viewport actions. Mouse actions for zooming/paning are currently bound as direct listeners and therefore alway on.

2025-03-26 12:57 UTC, tortmayr approved these changes
Thanks a lot. LGTM! 👍🏼

2025-03-26 12:57 UTC, merged