Various minor improvements
eclipse-glsp/glsp-client pull request #401
Opened 2024-11-25 11:53 UTC by tortmayr

#### What it does

- Merge *-default.ts implementation files of `FeedbackActionDispatcher` and `HelperLineManager` with the the interface definition files. The split is no longer necessary since we resolved potential circular dependency issues
- Ensure that we consistently use the `LazyInjector` over dedicated async providers and deprecate existing provider injection
- Fix a bug in the `FocusTracker` where we could end up in an invalid state on startup (diagram active but .diagramElement is undefined). This mostly occurred in standalone contexts (Diagram element is root => no focus change => handle gets never invoked)

#### How to test

#### Follow-ups

#### Changelog

-   [ ] This PR should be mentioned in the changelog
-   [ ] This PR introduces a breaking change (if yes, provide more details below for the changelog and the migration guide)

2024-11-25 12:21 UTC, martin-fleck-at requested changes
Change looks good to me overall but I wonder whether the focus tracking needs to be correctly initialized. Also the PR has merge conflicts. Other than that, I like the cleanup and various improvements, thank you Tobias!

2024-11-25 12:21 UTC, martin-fleck-at commented on packages/client/src/base/focus/focus-tracker.ts
>      protected _hasFocus = true;
I wonder if that should really be true now that we actually track the focus change in the beginning?

2024-11-25 12:21 UTC, martin-fleck-at commented on packages/client/src/base/focus/focus-tracker.ts
>          this._hasFocus = action.hasFocus;
This should probably be initialized correctly somehow.

2024-12-05 04:08 UTC, tortmayr commented
Thanks for the review Martin. I decided to revert the focus tracker fix for now.
As you said, simply setting the focus to true on init is probably not the right approach and we need to come up with a proper solution. Since this potentially also will affect all integration projects i decided to handle this in a follow-up.
It`s a non-critical release anyways so we can fix this issue later in one of the next release cycles.

2024-12-06 09:16 UTC, martin-fleck-at approved these changes
I'm fine with handling the focus tracking in a follow-up issue. Other than that, everything looks good to me, thank you Tobias!

2024-12-06 10:07 UTC, merged